apiVersion: apps/v1
kind: Deployment
metadata:
  name: drkiq
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: app
  template:
    metadata:
      labels:
        tier: app
        app: drkiq
    spec:
      initContainers:
      - name: init-myservice
        image: ib-task_drkiq:latest
        imagePullPolicy: Never
        command: ['sh', '-c', 'rake db:reset && rake db:migrate']
        envFrom:
        - configMapRef:
            name: drkiq-env
        env:
          - name: SECRET_TOKEN
            valueFrom:
              secretKeyRef:
                name: drkiqsecrettoken
                key: SECRET_TOKEN

          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: postgrespassword
                key: POSTGRES_URL

      containers:
      - name: drkiq
        image: drkiq:latest # make sure you've run 'minikube image load ib-task_drkiq:latest' first
        imagePullPolicy: Never # to be removed if we use a real registry
        ports:
          - containerPort: 8010
        envFrom:
        - configMapRef:
            name: drkiq-env
        env:
          - name: SECRET_TOKEN
            valueFrom:
              secretKeyRef:
                name: drkiqsecrettoken
                key: SECRET_TOKEN

          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: postgrespassword
                key: POSTGRES_URL
---

apiVersion: v1
kind: Service
metadata:
   name: drkiq
spec:
  ports:
  - port: 8010
    targetPort: 8010
  selector:
    app: drkiq


