apiVersion: v1
kind: ConfigMap
metadata:
  name: drkiq-env
  namespace: default
data:
  WORKER_PROCESSES: "1"
  LISTEN_ON: 0.0.0.0:8010
  CACHE_URL: redis://redis-service:6379/0
  JOB_WORKER_URL: redis://redis-service:6379/0
