apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        command: ["nginx"]
        args: ["-g", "daemon off;"]
        ports:
          - containerPort: 8020
        volumeMounts:
        - name: "config-volume"
          mountPath: "/etc/nginx/conf.d/reverse-proxy.conf"
          subPath: "reverse-proxy.conf"
      volumes:
        - name: config-volume
          configMap:
            name: nginx-config
---

apiVersion: v1
kind: Service
metadata:
   name: nginx
spec:
  ports:
  - port: 8020
    targetPort: 8020
  selector:
    tier: frontend
  type: NodePort


