apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drkiq-postgres
  labels:
    tier: db
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drkiq-redis
  labels:
    tier: cache
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi

